#!/bin/bash
echo 'RHEA executable directory: ' $RHEA_EXE_DIR
mpirun -np 8 --hostfile $RHEA_EXE_DIR/my-hostfile --mca btl_base_warn_component_unused 0 $RHEA_EXE_DIR/RHEA.exe $RHEA_EXE_DIR/configuration_file.yaml 0 $RHEA_EXE_DIR/restart_data_file.h5 0.001 0.10201 0.0 False 0 > /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/examples/RL_3D_turbulent_channel_flow/train/train_2024-09-19--08-48-09--901b/mpi_output/mpi_output_ensemble0_step0.out 2>&1 & \
mpirun -np 8 --hostfile $RHEA_EXE_DIR/my-hostfile --mca btl_base_warn_component_unused 0 $RHEA_EXE_DIR/RHEA.exe $RHEA_EXE_DIR/configuration_file.yaml 1 $RHEA_EXE_DIR/restart_data_file.h5 0.001 0.10201 0.0 False 0 > /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/examples/RL_3D_turbulent_channel_flow/train/train_2024-09-19--08-48-09--901b/mpi_output/mpi_output_ensemble1_step0.out 2>&1 & \
mpirun -np 8 --hostfile $RHEA_EXE_DIR/my-hostfile --mca btl_base_warn_component_unused 0 $RHEA_EXE_DIR/RHEA.exe $RHEA_EXE_DIR/configuration_file.yaml 2 $RHEA_EXE_DIR/restart_data_file.h5 0.001 0.10201 0.0 False 0 > /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/examples/RL_3D_turbulent_channel_flow/train/train_2024-09-19--08-48-09--901b/mpi_output/mpi_output_ensemble2_step0.out 2>&1 & \
mpirun -np 8 --hostfile $RHEA_EXE_DIR/my-hostfile --mca btl_base_warn_component_unused 0 $RHEA_EXE_DIR/RHEA.exe $RHEA_EXE_DIR/configuration_file.yaml 3 $RHEA_EXE_DIR/restart_data_file.h5 0.001 0.10201 0.0 False 0 > /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/examples/RL_3D_turbulent_channel_flow/train/train_2024-09-19--08-48-09--901b/mpi_output/mpi_output_ensemble3_step0.out 2>&1 & \
mpirun -np 8 --hostfile $RHEA_EXE_DIR/my-hostfile --mca btl_base_warn_component_unused 0 $RHEA_EXE_DIR/RHEA.exe $RHEA_EXE_DIR/configuration_file.yaml 4 $RHEA_EXE_DIR/restart_data_file.h5 0.001 0.10201 0.0 False 0 > /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/examples/RL_3D_turbulent_channel_flow/train/train_2024-09-19--08-48-09--901b/mpi_output/mpi_output_ensemble4_step0.out 2>&1 & \
mpirun -np 8 --hostfile $RHEA_EXE_DIR/my-hostfile --mca btl_base_warn_component_unused 0 $RHEA_EXE_DIR/RHEA.exe $RHEA_EXE_DIR/configuration_file.yaml 5 $RHEA_EXE_DIR/restart_data_file.h5 0.001 0.10201 0.0 False 0 > /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/examples/RL_3D_turbulent_channel_flow/train/train_2024-09-19--08-48-09--901b/mpi_output/mpi_output_ensemble5_step0.out 2>&1 & \
mpirun -np 8 --hostfile $RHEA_EXE_DIR/my-hostfile --mca btl_base_warn_component_unused 0 $RHEA_EXE_DIR/RHEA.exe $RHEA_EXE_DIR/configuration_file.yaml 6 $RHEA_EXE_DIR/restart_data_file.h5 0.001 0.10201 0.0 False 0 > /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/examples/RL_3D_turbulent_channel_flow/train/train_2024-09-19--08-48-09--901b/mpi_output/mpi_output_ensemble6_step0.out 2>&1 & \
mpirun -np 8 --hostfile $RHEA_EXE_DIR/my-hostfile --mca btl_base_warn_component_unused 0 $RHEA_EXE_DIR/RHEA.exe $RHEA_EXE_DIR/configuration_file.yaml 7 $RHEA_EXE_DIR/restart_data_file.h5 0.001 0.10201 0.0 False 0 > /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/examples/RL_3D_turbulent_channel_flow/train/train_2024-09-19--08-48-09--901b/mpi_output/mpi_output_ensemble7_step0.out 2>&1
