#!/bin/bash
echo 'RHEA executable directory: /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/ProjectRHEA/examples/RL_3D_turbulent_channel_flow'
mpirun -np 8 --hostfile /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/ProjectRHEA/examples/RL_3D_turbulent_channel_flow/my-hostfile --mca btl_base_warn_component_unused 0 /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/ProjectRHEA/examples/RL_3D_turbulent_channel_flow/RHEA.exe /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/ProjectRHEA/examples/RL_3D_turbulent_channel_flow/configuration_file.yaml 0 /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/ProjectRHEA/examples/RL_3D_turbulent_channel_flow/restart_data_file.h5 0.0005 0.20055 0.0 False 0 > /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/examples/RL_3D_turbulent_channel_flow/train/train_2024-10-10--15-14-29--3ddd/mpi_output/mpi_output_ensemble0_step000000.out 2>&1 &
pid0=$!
mpirun -np 8 --hostfile /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/ProjectRHEA/examples/RL_3D_turbulent_channel_flow/my-hostfile --mca btl_base_warn_component_unused 0 /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/ProjectRHEA/examples/RL_3D_turbulent_channel_flow/RHEA.exe /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/ProjectRHEA/examples/RL_3D_turbulent_channel_flow/configuration_file.yaml 1 /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/ProjectRHEA/examples/RL_3D_turbulent_channel_flow/restart_data_file.h5 0.0005 0.20055 0.0 False 0 > /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/examples/RL_3D_turbulent_channel_flow/train/train_2024-10-10--15-14-29--3ddd/mpi_output/mpi_output_ensemble1_step000000.out 2>&1 &
pid1=$!
mpirun -np 8 --hostfile /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/ProjectRHEA/examples/RL_3D_turbulent_channel_flow/my-hostfile --mca btl_base_warn_component_unused 0 /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/ProjectRHEA/examples/RL_3D_turbulent_channel_flow/RHEA.exe /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/ProjectRHEA/examples/RL_3D_turbulent_channel_flow/configuration_file.yaml 2 /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/ProjectRHEA/examples/RL_3D_turbulent_channel_flow/restart_data_file.h5 0.0005 0.20055 0.0 False 0 > /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/examples/RL_3D_turbulent_channel_flow/train/train_2024-10-10--15-14-29--3ddd/mpi_output/mpi_output_ensemble2_step000000.out 2>&1 &
pid2=$!
mpirun -np 8 --hostfile /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/ProjectRHEA/examples/RL_3D_turbulent_channel_flow/my-hostfile --mca btl_base_warn_component_unused 0 /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/ProjectRHEA/examples/RL_3D_turbulent_channel_flow/RHEA.exe /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/ProjectRHEA/examples/RL_3D_turbulent_channel_flow/configuration_file.yaml 3 /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/ProjectRHEA/examples/RL_3D_turbulent_channel_flow/restart_data_file.h5 0.0005 0.20055 0.0 False 0 > /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/examples/RL_3D_turbulent_channel_flow/train/train_2024-10-10--15-14-29--3ddd/mpi_output/mpi_output_ensemble3_step000000.out 2>&1 &
pid3=$!
mpirun -np 8 --hostfile /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/ProjectRHEA/examples/RL_3D_turbulent_channel_flow/my-hostfile --mca btl_base_warn_component_unused 0 /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/ProjectRHEA/examples/RL_3D_turbulent_channel_flow/RHEA.exe /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/ProjectRHEA/examples/RL_3D_turbulent_channel_flow/configuration_file.yaml 4 /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/ProjectRHEA/examples/RL_3D_turbulent_channel_flow/restart_data_file.h5 0.0005 0.20055 0.0 False 0 > /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/examples/RL_3D_turbulent_channel_flow/train/train_2024-10-10--15-14-29--3ddd/mpi_output/mpi_output_ensemble4_step000000.out 2>&1 &
pid4=$!
mpirun -np 8 --hostfile /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/ProjectRHEA/examples/RL_3D_turbulent_channel_flow/my-hostfile --mca btl_base_warn_component_unused 0 /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/ProjectRHEA/examples/RL_3D_turbulent_channel_flow/RHEA.exe /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/ProjectRHEA/examples/RL_3D_turbulent_channel_flow/configuration_file.yaml 5 /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/ProjectRHEA/examples/RL_3D_turbulent_channel_flow/restart_data_file.h5 0.0005 0.20055 0.0 False 0 > /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/examples/RL_3D_turbulent_channel_flow/train/train_2024-10-10--15-14-29--3ddd/mpi_output/mpi_output_ensemble5_step000000.out 2>&1 &
pid5=$!
mpirun -np 8 --hostfile /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/ProjectRHEA/examples/RL_3D_turbulent_channel_flow/my-hostfile --mca btl_base_warn_component_unused 0 /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/ProjectRHEA/examples/RL_3D_turbulent_channel_flow/RHEA.exe /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/ProjectRHEA/examples/RL_3D_turbulent_channel_flow/configuration_file.yaml 6 /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/ProjectRHEA/examples/RL_3D_turbulent_channel_flow/restart_data_file.h5 0.0005 0.20055 0.0 False 0 > /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/examples/RL_3D_turbulent_channel_flow/train/train_2024-10-10--15-14-29--3ddd/mpi_output/mpi_output_ensemble6_step000000.out 2>&1 &
pid6=$!
mpirun -np 8 --hostfile /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/ProjectRHEA/examples/RL_3D_turbulent_channel_flow/my-hostfile --mca btl_base_warn_component_unused 0 /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/ProjectRHEA/examples/RL_3D_turbulent_channel_flow/RHEA.exe /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/ProjectRHEA/examples/RL_3D_turbulent_channel_flow/configuration_file.yaml 7 /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/ProjectRHEA/examples/RL_3D_turbulent_channel_flow/restart_data_file.h5 0.0005 0.20055 0.0 False 0 > /home/jofre/Nuria/repositories/RL_3d_turbulent_channel_flow/examples/RL_3D_turbulent_channel_flow/train/train_2024-10-10--15-14-29--3ddd/mpi_output/mpi_output_ensemble7_step000000.out 2>&1 &
pid7=$!
wait $pid0 $pid1 $pid2 $pid3 $pid4 $pid5 $pid6 $pid7
echo 'All MPI processes have completed.'
